### ISSUE TITLE
Add ability to add ssh key to github

### ISSUE THREAD

**Issue by KonnorRogers** [ParamagicDev/vps-setup#5]
An appropriate GraphQL request in githubs API v4 does not exist. So therefore I will use the v3 api found here. 

[Github v3 Api for SSH keys](https://developer.github.com/v3/users/keys/)

Here is the code i came up with the adequately pull in the keys to github via Ruby

[Ruby code using rest-client / Net::HTTP](https://gist.github.com/ParamagicDev/c835136c8e303a406d8addd78d9287fd)

In order to avoid using passwords over a request, instead I opt to use API tokens for authentication. You can add one here:

[API token generator in Github](https://github.com/settings/tokens)

Make sure your token has write:public_key access for a scope.

**Comment by ParamagicDev** [comment]
Because you'll be on a new server, it only makes sense you won't have an appropriate ssh key, going to need to do a GraphQL request.

**Comment by ParamagicDev** [comment]
Will create a guide for Ruby graphql requests

**Comment by ParamagicDev** [comment]
using graphql requests [Github graphql requests](https://developer.github.com/v4/)

**Comment by KonnorRogers** [comment]
Implemented.
